name: RandomDrops-OG
author: Sekalol15
description: Makes various items obtainable. Crafted by TrueOG Network.
website: https://github.com/true-og/RandomDrops-OG
version: '${version}'
api-version: '${apiVersion}' 
main: plugin.RandomDropsOG
